org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
# iOS: don't try to build simulator frameworks for x86_64 on Apple Silicon
kotlin.native.ignoreDisabledTargets=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
